### ISSUE TITLE
SSH menu item not working with iTerm/iTerm2

### ISSUE THREAD

**Issue by briantully** [lanayotech/vagrant-manager#100]
Within the past week, the SSH menu item has stopped working for me. I have been using iTerm2 2.1 and the menu item would neither open a new terminal window nor would it run the command `vagrant ssh`. It would occasionally work if i had an existing iTerm window active. But now that is not the case. I recently upgraded iTerm to the 2.9 beta, and it is still not working. 

Any idea what I can do to get the ssh menu item working with iTerm again?

**Comment by amitailanciano** [comment]
Hi Brian, what exactly happens when you click the SSH menu item? does it just do nothing?

**Comment by briantully** [comment]
Yes, it just does nothing. It doesn't open iTerm, nor does it activate the iTerm window if iTerm is already open. Also, if iTerm is the active app/window, it does not enter the vagrant ssh command. Thanks!

**Comment by Ipstenu** [comment]
This is working for me just fine on 10.10.4

**Comment by morokin** [comment]
Confirming this issue.
"SSH" and  "Open in terminal" are not working, just do nothing.
OS X 10.10.4
Vagrant Manager 2.4.4
iTerm2 Build 2.9.20150810-nightly

**Comment by phmullins** [comment]
I'm having the same issue. Vagrant Manager will not open iTerm2 when "Terminal Preference" is set to iTerm/iTerm2. However, it will open Terminal when "Terminal Preference" is set to Terminal. 

OS X 10.10.5 (14F27)
Vagrant Manager iTerm2
iTerm2 Build 2.9.20150830

**Comment by chriswayoub** [comment]
The AppleScript syntax changed for version 2.9. I have put together working AppleScript for 2.9, but I haven't been able to make a version that will work for both 2.9 and earlier versions. I'm not an AppleScript expert and I haven't had much luck on Google so if anyone can provide some assistance it would be appreciated. Here is the AppleScript that works for 2.9:

```
tell application "iTerm"
	activate
	tell current window
		create tab with default profile
		tell current session
			write text "echo 'test'"
		end tell
	end tell
end tell
```

and here is the current AppleScript we have for earlier versions (I'm testing on 2.1.4):

```
tell application "iTerm"
	tell current terminal
		launch session "Default Session"
		delay 0.15
		activate
		tell the last session
			write text "echo 'test'"
		end tell
	end tell
end tell
```

**Comment by msr** [comment]
You could do something like this:

```applescript
set v2_script to "
tell application \"iTerm\"
  tell current terminal
    launch session \"Default Session\"
    delay 0.15
    activate
    tell the last session
      write text \"echo 'test'\"
    end tell
  end tell
end tell"

set v3_script to "
tell application \"iTerm\"
  activate
  tell current window
    create tab with default profile
    tell current session
      write text \"echo 'test'\"
    end tell
  end tell
end tell"

if application "iTerm"'s version >= "2.9" then
  run script v3_script
else
  run script v2_script
end
```
