### ISSUE TITLE
Please do not ignore the result of the global-status task

### ISSUE THREAD

**Issue by ruurd** [lanayotech/vagrant-manager#102]
In VagrantGlobalStatusScanner implementation the result of the task is only considered if the result code of the subprocess is 0. In all other cases the status of the machines is set to not running per default. It is possible that the global status subtask returns a different result. Please make sure that that result is presented to the user if he manually invokes a refresh of the status.

**Comment by amitailanciano** [comment]
[release 2.4.4](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.4) will now show an error notification if the task was unsuccessful, thanks for the suggestion

**Comment by ruurd** [comment]
Excellent. By the way - it would be a good thing to also show the command executed at that moment so one can retry this in the console? This usually shows more error information.

**Comment by amitailanciano** [comment]
It does that too :)

The notification will say 

```
`vagrant global-status --prune` command encountered an error, run command in a terminal window to debug
```

See https://github.com/lanayotech/vagrant-manager/commit/b2b9462c4fae6084c0413232de925abd32859754

**Comment by ruurd** [comment]
\0/ you can read my mind! Excellent!
