### ISSUE TITLE
Up Status Not Updating After Start

### ISSUE THREAD

**Issue by jjanusch** [lanayotech/vagrant-manager#103]
If I leave a machine running when I shut down my computer, Vagrant Manager doesn't update when I start my computer up next. It will still show that machine as up (displayed as green) in the Vagrant Manager window, even though the vagrant machine is not actually running. It goes away after a manual refresh.

Vagrant 1.7.4
OS X 10.10.4
Vagrant Manager 2.4.2

**Comment by amitailanciano** [comment]
See #111 for a temporary resolution to this issue

**Comment by chriswayoub** [comment]
This should be resolved in 2.5.0. If you are still having this issue, please re-open the ticket.
