### ISSUE TITLE
2.4.3 on Mac doesn't show status properly

### ISSUE THREAD

**Issue by Ipstenu** [lanayotech/vagrant-manager#106]
Newest version doesn't show up and down status properly.

I just updated today and while my box is up (vvv.dev in the screenshot) it shows as offline in the app.

https://cloudup.com/ct-Hx-VF3tH

Related to #103 perhaps.

**Comment by amitailanciano** [comment]
Did you see any notifications about `vagrant global-status --prune` failing? You can two finger swipe from the right of your trackpad to see missed notifications, try running it in your terminal window and make sure you're not getting any errors (I'm guessing you might since no other machines appear in the list except your bookmarks)

**Comment by Ipstenu** [comment]
$ vagrant global-status --prune
There was an error loading a Vagrantfile. The file being loaded and the error message are shown below. This is usually caused by a syntax error.

Path: /Users/mika/Sites/HGV/Vagrantfile
Line number: 299
Message: Errno::ENOENT: No such file or directory - ./provisioning/default-install.yml

**Comment by amitailanciano** [comment]
See #105 for the fix

**Comment by Ipstenu** [comment]
Well darn :D I'm not getting the notifications on failure, though, which is odd. Reporting to HGV! Thanks, you rock!

**Comment by amitailanciano** [comment]
No problem! :+1: I'll take a look as to why you might not be getting that notification as well

**Comment by Ipstenu** [comment]
I manually expanded notifications to be sure and still nothing from VM there. I checked in SysPref and it's not listed as an app in my Notification center. o.O

**Comment by amitailanciano** [comment]
@Ipstenu there was indeed an issue with the notifications, would you mind giving this build a shot? I want to verify that the issue is resolved

https://www.dropbox.com/s/hfgey5y0d4jid1i/Vagrant%20Manager%202.4.4b.app.zip?dl=1

**Comment by Ipstenu** [comment]
I had to reinstall the broken image first.

Yes, I get alerts! Yay!
