### ISSUE TITLE
Updated to 2.4.4, doesn't detect VMs 

### ISSUE THREAD

**Issue by andrew40** [lanayotech/vagrant-manager#109]
Have re-installed everything (literally) and using MercuryWP Vagrant as a sole VM.

Upgraded to 2.4.4 and now getting 'vagrant global-status --prune' command encountered an error, run command in terminal window to debug. So I did and this is the output.

vagrant global-status --prune
id       name   provider   state   directory
-----------------------------------------------------------------------
c4027c9  hgv    virtualbox running /Users/andrewwilkinson/Vagrant/hgv

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
/Users/andrewwilkinson/Vagrant/hgv/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/andrewwilkinson/Vagrant/hgv/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here

Vagrant Manager is still not picking this VM up. Any ideas?

**Comment by amitailanciano** [comment]
sounds like the same as #107 

I'll put together a debug build this evening

**Comment by andrew40** [comment]
Yes just read the comments on there, would you like me to close this and watch #107

**Comment by amitailanciano** [comment]
that'd be great, thanks
