### ISSUE TITLE
No "Up" option after destroy

### ISSUE THREAD

**Issue by VadimDez** [lanayotech/vagrant-manager#110]
After destroying a bookmarked vagrant, no way to perform an up.
Up is shown only after relaunch.
Version 2.4.4
![screen shot 2015-08-14 at 10 04 14](https://cloud.githubusercontent.com/assets/3748453/9269640/e930e336-426b-11e5-8646-0b488b4ea32c.png)

**Comment by chriswayoub** [comment]
This should be resolved in 2.5.0. If you are still having this issue, please re-open the ticket.
