### ISSUE TITLE
Sometimes "vagrant global-status --prune" output is incorrect

### ISSUE THREAD

**Issue by amitailanciano** [lanayotech/vagrant-manager#111]
Steps to reproduce:

1 - Use NFS
2 - Up a machine
3 - Halt the machine
4 - Delete contents of /etc/exports
5 - `vagrant reload` from the command line on that machine

`vagrant global-status --prune` will show that the machine is in a poweroff state, while `vagrant status` will show that the machine is running (which is correct).

Due to this and some other issues being reported, I will probably have to shelve the usage of `vagrant global-status --prune` as the sole detection source and revert to the more power hungry `vagrant status` in each detected directory approach

I recommend using [2.4.1](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.1) until this issue is resolved

**Comment by andrew40** [comment]
2.4.1 works like a charm :) thanks..

Hopefully you'll get it sorted..

**Comment by Londeren** [comment]
Same error in 2.4.4

**Comment by thorsten** [comment]
Same error here with OS X 10.10.5, Vagrant Manager 2.4.4 and Vagrant 1.7.4

**Comment by chriswayoub** [comment]
Machine state detection no longer uses vagrant global-status, so this issue should be resolved. If you are still having problems related to this, please re-open this issue.

**Comment by thorsten** [comment]
Works again, thanks a lot! :+1:
