### ISSUE TITLE
Add "Edit Vagrantfile" to each of the VM menus

### ISSUE THREAD

**Issue by fcerbell** [lanayotech/vagrant-manager#112]
It would be nice to be able to open the Vagrantfile from the menu (a menu item "edit vagrant file" next to "Open in terminal"). It could use the default text editor.

**Comment by randycasburn** [comment]
+1 For this feature request

**Comment by phmullins** [comment]
Excellent idea! +1

**Comment by andrew40** [comment]
+1

**Comment by chriswayoub** [comment]
This feature has been added in version 2.5.0
