### ISSUE TITLE
Vagrant Manager not showing most of my machines anymore

### ISSUE THREAD

**Issue by teeli** [lanayotech/vagrant-manager#116]
So, in the last few versions (at least 2.4.x) Vagrant Manager has stopped showing most of my machines. It shows like 5 out of 20-30 machines and before it showed them all. They're all initialised virtualbox machines and some of them are running "all the itme" and still not shown in the menu. All of them are running in basically the same directory structure (~/Projects/<project-name>/Vagrantfile). Any ideas why this is happening?

Currently I have Vagrant Manager 2.4.4, Vagrant 1.7.4 and Virtualbox 5.0.4 (latest stable versions as of writing this)

**Comment by amitailanciano** [comment]
2.4.4 uses only `global-status` for detection but there are some issues #111

I recommend using 2.4.1 for now

**Comment by teeli** [comment]
Thanks.
