### ISSUE TITLE
2.5.0 not working on OSX El Capitan (10.11.1)

### ISSUE THREAD

**Issue by sshrestha-navarts** [lanayotech/vagrant-manager#119]
I can get 2.4.4 to work correctly, however 2.5.0 shows an icon in menubar and then abruptly dissapears.

Using Homebrew Cask to install

**Comment by sshrestha-navarts** [comment]
Same behavior with directly downloading and installing.

**Comment by amitailanciano** [comment]
We'll try to put out a debug version for you soon
