### ISSUE TITLE
Look for vb.name in Vagrantfile

### ISSUE THREAD

**Issue by urre** [lanayotech/vagrant-manager#120]
Would be great if Vagrant Manager could use vb.name if this is provided in the Vagrantfile. As a default name instead of folder name.

**Comment by amitailanciano** [comment]
That has been the default behavior since release so we can't really change it at this point, but there is an option in the Preferences to include the name of the box.

**Comment by urre** [comment]
thanks @amitailanciano, i had missed those settings!
