### ISSUE TITLE
automatically halt all machines on shutdown

### ISSUE THREAD

**Issue by nostalgicdodo** [lanayotech/vagrant-manager#121]
I forget to halt the machines most of the time. A dialog prompting to halt the machines would be helpful. If they could automatically halted, that would be awesome.

**Comment by esszett** [comment]
Same here, I agree.

**Comment by maces** [comment]
duplicate of #90

**Comment by chriswayoub** [comment]
This feature has been implemented in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
