### ISSUE TITLE
vagrant up and vagrant sssh with one click

### ISSUE THREAD

**Issue by n3r0-ch** [lanayotech/vagrant-manager#125]
It would be very useful to have a button on a stopped to machine to run vagrant up and vagrant ssh with one click. Now i have to wait until the machine is up and then open the menu a second time.

**Comment by amitailanciano** [comment]
We'll look into this, maybe some kind of configuration window where you can build your own vagrant command chains and save them to be included in the actions list

**Comment by sidewinder12s** [comment]
I came up with a bash alias to run vagrant up & vagrant ssh, maybe if you support running custom commands you could solve this and #138

**Comment by chriswayoub** [comment]
This feature has been implemented in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
