### ISSUE TITLE
Vagrant 1.8 boxes are not showing

### ISSUE THREAD

**Issue by juanfcocontreras** [lanayotech/vagrant-manager#126]
Since I have updated to Vagrant 1.8.0, no virtualbox machines are auto-detected. I have to add them manually as bookmarks. They were shown with Vagrant 1.7.4. Also, if I click on "Check for Vagrant updates", a message "There was a problem checking your Vagrant version". VMs seems to work fine if they are added as bookmarks.

 I have installed Vagrant with homebrew in OS X 10.11.2, and configuration is in default folders (~/.vagrant.d) and vagrant global-status is:

vagrant global-status

id       name    provider   state    directory
7dbd50b  default virtualbox poweroff /Users/xxxxx/Development/scotch-box/my-project

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"

**Comment by majksner** [comment]
+ 1 Parallels Boxes not showing up.

**Comment by wernsting** [comment]
+1
Haven't tried an older version of vagrant, but even with bookmarks I cannot get it to see my boxes

**Comment by bezhermoso** [comment]
+1

I have this issue as well (for me, it never worked with Vagrant 1.7.* either).

I get these errors in `Console.app` when I try to do something (_Refresh_, _Check For Vagrant Updates_, etc)

<img width="874" alt="screen shot 2016-02-27 at 4 41 00 pm" src="https://cloud.githubusercontent.com/assets/1437428/13376451/b8bf9b92-dd71-11e5-88a5-55e9e1198f22.png">

**Comment by amitailanciano** [comment]
@majksner @wernsting @bezhermoso is this still an issue with the latest vagrant & vagrant-manager?

**Comment by juanfcocontreras** [comment]
It's working well for me in latest versions.

Thanks.
