### ISSUE TITLE
Doesn't recognise Vagrant 1.8.1 when checking for updates

### ISSUE THREAD

**Issue by the-holger** [lanayotech/vagrant-manager#127]
Hi there!

I've noticed on Mac OS X El Capitan (10.11.3) that the menu item for "Check For Vagrant Updates" is showing the ! next to it. Clicking on it results in the popup window informing me that a newer version of Vagrant was available, it correctly shows the latest version as 1.8.1 but for the Current version it says "output". (On the command line vagrant --version results in "Vagrant 1.8.1").

<img width="420" alt="update window" src="https://cloud.githubusercontent.com/assets/1640406/12074682/4724b5c6-b161-11e5-8d4a-4b3518047104.png">
<img width="243" alt="menu" src="https://cloud.githubusercontent.com/assets/1640406/12074683/47496d8a-b161-11e5-95a4-0dcf40513a00.png">

**Comment by andrew40** [comment]
I have upgraded Vagrant to 1.8.1 and checked it is installed with vagrant --version, but vagrant manager still shows the alert icon that i have not upgraded in the dropdown 'Check for Updates'. everything else appears to work ok. 

El Capitain 10.11.2
Vagrant Manager 2.5.0
Vagrant 1.8.1

**Comment by chriswayoub** [comment]
This issue has been addressed in release 2.5.1
