### ISSUE TITLE
Add VMware AppCatalyst as provider

### ISSUE THREAD

**Issue by brianannis** [lanayotech/vagrant-manager#129]
Would it be possible to add VMware AppCatalyst as a Vagrant provider? All state information is accessible through their REST API a la prlctl and vboxmanage. AppCatalyst is handy because it runs VMware boxes headless without a Fusion / Vagrant plugin license.

To get available VMs:

```
http://localhost:8080/api/vms
["vagrant-d3f0c18f-75ee-4990-8cf2-8ef757813b22"]
```

To get power state:

```
http://localhost:8080/api/vms/power/vagrant-d3f0c18f-75ee-4990-8cf2-8ef757813b22
{"code":200,"message":"powered on"}
```

Everything else should be reasonably close to the vmware_fusion implementation.

**Comment by chriswayoub** [comment]
I'm not familiar with AppCatalyst, do you still control the boxes with Vagrant commands even without the Vagrant plugin? (ie: vagrant up, vagrant down, etc)

**Comment by brianannis** [comment]
As far as I can tell, all of the Vagrant actions are supported via the [VMware AppCatalyst plugin](https://github.com/vmware/vagrant-vmware-appcatalyst])

FMI: [VMware Blog](https://blogs.vmware.com/cloudnative/vmware-appcatalyst/)

**Comment by brianannis** [comment]
VMware Fusion is free now and AppCatalyst is EOL, closing
