### ISSUE TITLE
Halt all

### ISSUE THREAD

**Issue by Decipher** [lanayotech/vagrant-manager#131]
I often have upwards of 5 vagrant environments or more running at once, but at the end of the work day I like to ensure that all environments are halted. Halting each environment one-by-one is time consuming, it'd be great if there was a **Halt all** option.

**Comment by amitailanciano** [comment]
You can halt all your machines by navigating to All Machines -> Halt

**Comment by Decipher** [comment]
You are right, I entirely missed that option. Thanks for the great work!

**Comment by amitailanciano** [comment]
Thanks!
