### ISSUE TITLE
Sparkle SUFeedURL is vulnerable

### ISSUE THREAD

**Issue by rderewianko** [lanayotech/vagrant-manager#132]
Hello,

Your current SUFeedURL is:[http://api.lanayo.com/appcast/vagrant_manager.xml]( http://api.lanayo.com/appcast/vagrant_manager.xml)
as per a recently detected vulnerability detected. 
[More Info](https://vulnsec.com/2016/osx-apps-vulnerabilities/) your url needs to be updated to mitigate against this kind of attack.

**Comment by ruurd** [comment]
This vulnerability has been weaponized in the mean time. https://www.reddit.com/r/netsec/comments/43ewlu/osx_mass_pwning_using_bettercap_and_the_sparkle/

Please expedite.

**Comment by seansgm** [comment]
Do we have an update on when this could be patched please?

`$ defaults read /Volumes/Vagrant\ Manager/Vagrant\ Manager.app/Contents/Info.plist CFBundleShortVersionString
2.5.1
$ defaults read /Volumes/Vagrant\ Manager/Vagrant\ Manager.app/Contents/Info.plist SUFeedURL
http://api.lanayo.com/appcast/vagrant_manager.xml
$ defaults read /Volumes/Vagrant\ Manager/Vagrant\ Manager.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Info.plist CFBundleShortVersionString
1.6 git`

https://vulnsec.com/2016/osx-apps-vulnerabilities/

**Comment by chriswayoub** [comment]
We're packaging a release that addresses this issue. It will most likely be available sometime today.

**Comment by chriswayoub** [comment]
Version 2.5.3 addresses this issue

**Comment by seansgm** [comment]
Thanks, appreciated

**Comment by ruurd** [comment]
Fixed. Great job guys!
