### ISSUE TITLE
Allow setting Preferences via Command Line for Scripted Install

### ISSUE THREAD

**Issue by mikeschinkel** [lanayotech/vagrant-manager#133]
It would be great if you provide a capability to set preferences via command line so I can fully script installation.  

Or maybe this is already possible?

**Comment by chriswayoub** [comment]
There is not currently any command line functionality built in to Vagrant Manager, but you should be able to set the preferences via the `defaults` OS X command that is documented here:

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/defaults.1.html

Here's a quick example that will enable auto-refresh at 15 minute intervals:

```
defaults write lanayo.Vagrant-Manager "refreshEvery" "1"
defaults write lanayo.Vagrant-Manager "refreshEveryInterval" "900"
```

The list of available preferences isn't documented anywhere, but once you've set them through the Preferences window in the application, you can get a list of them:

```
defaults read lanayo.Vagrant-Manager
```

It's very likely that setting these preferences while Vagrant Manager is running will not take effect until the app is restarted, so it would be safest to set the preferences before you start the application.

**Comment by mikeschinkel** [comment]
Thanks!
