### ISSUE TITLE
OSX warning: Failed to connect (_consoleX) outlet from (NSApplication)

### ISSUE THREAD

**Issue by mehany** [lanayotech/vagrant-manager#134]
I use vagrant manager everyday in my development. Recently i started to get the below error in my OS error messages log and I can't ssh to the server in question from vagrant manager menu - I hover on the server name and click ssh.

```
Console[282]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable
```

Vagrant manager 2.5.0
Vagrant 1.7.4
osx 10.11

The vagrant box I am using is laravel/homestead

I also get few other warnings but I am not sure how can I report this issue in a useful way, so please ask! The above warning is the first one that appears soon after I <code> up </code> the server in question.

Edit: I think this is related to ssh settings being changed. I tried to load my VM nad I got this output

```
(B[m==> default: Attempting graceful shutdown of VM...
default: Guest communication could not be established! This is usually because
default: SSH is not running, the authentication information was changed,
default: or some other networking issue. Vagrant will force halt, if
default: capable.
```

But I didn't change the ssh settings nor keys, may you advice on how to avoid this?

**Comment by chriswayoub** [comment]
We are looking into this. I'll let you know if we need more info from you.
