### ISSUE TITLE
OSX cannot set another default editor

### ISSUE THREAD

**Issue by andrewi-wd** [lanayotech/vagrant-manager#136]
* OS: OSX 10.11.3
* vagrant-manager: 2.5.3

I am trying to change the default editor in app preferences to 'nano' instead of 'vim'.

Steps to recreate:
* Open vagrant-manager preferences
* Select 'iTerm/iTerm2' option in Terminal Preference
* Select 'nano' option in Terminal Editor Preference
* Click 'done'
* Reopen vagrant-manager preferences
* 'vim' is selected by default in Terminal Editor Preference

Also, configured out, that Terminal Preference set to iTerm/iTerm2 some how influence on this, with very strange behaviour.

**Comment by andrewi-wd** [comment]
Found tricky workaround, which worked for me:

* open preferences
* set terminal to 'Terminal' and editor to 'vim'
* click done and reopen preferences
* set editor to 'nano'
* click done and reopen preferences
* set terminal to 'iTerm/iTerm2'
* click done

**Comment by chriswayoub** [comment]
Thanks for the detailed report! This has been fixed in commit ec05c2dc11c41813c737271c4e4c367f439d1abf

We'll include it in the next release.
