### ISSUE TITLE
OS X, issue on branch change

### ISSUE THREAD

**Issue by VadimDez** [lanayotech/vagrant-manager#137]
Prerequisites: two branches, for example master and develop. "master" has no vagrant configured yet, and "develop" has.
Being under "develop" branch (correct):
![screen shot 2016-03-23 at 09 46 32](https://cloud.githubusercontent.com/assets/3748453/13980033/71ff787a-f0dc-11e5-93d1-634ba9205922.png)

Switching to branch "master" (correct):
![screen shot 2016-03-23 at 09 43 28](https://cloud.githubusercontent.com/assets/3748453/13980059/90d91742-f0dc-11e5-8fb4-2fa0067fc37a.png)

And then after switching back to "develop" - options are not available after "refresh" anymore. Helps only restart.
![screen shot 2016-03-23 at 09 44 09](https://cloud.githubusercontent.com/assets/3748453/13980067/9fdc6f46-f0dc-11e5-84cf-95fa41fb8f5d.png)

**Comment by chriswayoub** [comment]
Thanks for the report, this has been fixed and will be included in the next release
