### ISSUE TITLE
Vagrant Manager does not work with plugins

### ISSUE THREAD

**Issue by mrpotatoes** [lanayotech/vagrant-manager#139]
Which is a shame because I'd prefer to use it instead of the command line to reboot my VM.

I tested this with https://github.com/emyl/vagrant-triggers.

In my Vagrantfile under `Vagrant.configure(2) do |config|`
```
config.trigger.after :up do
    run "vagrant ssh -c 'screen -Sdm rtail rtail-server --web-port 8080 --web-host \"192.168.50.4\"'"
    run "vagrant ssh -c 'cd /api; screen -Sdm api make vagrant'"
    run "vagrant ssh -c 'cd /api; screen -Sdm worker make vagrantWorker'"
    run "vagrant ssh -c 'cd  /ui; screen -Sdm ui make vagrant'"
  end
```

Here is the output from my terminal. The read is the `run` command executing in the shell.

![terminal](https://cloud.githubusercontent.com/assets/1066744/14183042/27b9eea6-f73c-11e5-9a2a-df5e6d2caa70.png)

Here is the Vagrant Manager
![vagrant manager](https://cloud.githubusercontent.com/assets/1066744/14183058/3d7f4ace-f73c-11e5-960b-275dd0b2bc9f.png)

Unfortunately it is not executing the command which is a part of a plugin that I've installed.

**Comment by chriswayoub** [comment]
Can you verify that the trigger runs when you `vagrant reload` from the command-line? It your screenshots, it looks like you are running `vagrant halt; vagrant up` and through Vagrant Manager you are doing a `vagrant reload`. Your example trigger is set to run on `config.trigger.after :up do`. I'm not familiar with that plugin, but it might not be running your commands on `vagrant reload`, only when you specifically call `vagrant up`.

**Comment by mrpotatoes** [comment]
Yes, you're 100% right.

The vagrant site says that reload is the same as halt + up but it isn't an alias for those commands. I put the reload in the trigger and it works just fine.
