### ISSUE TITLE
Hide task window

### ISSUE THREAD

**Issue by jamesrward** [lanayotech/vagrant-manager#140]
This is a feature request.  

For the most part I find the task window a nuisance.  While auto-close is a nice feature I would prefer to have it not come up at all.  I'm not sure what the options are for hiding the task window but ideally it would only become visible if something went wrong.  Otherwise I can just watch for the number to change on my taskbar to know when the "up" is complete.

If that is not possible than just an option to log the output of the task window so I can go look at it if my "up" happens to fail but keep the window hidden.

Vagrant Manager is awesome and I use it everyday.  Thanks to everyone involved.

**Comment by chriswayoub** [comment]
Some quick testing showed that this is possible, but it seems strange that there is no indication that anything is even happening at all until the command finishes. There would probably need to be some other indicator that an action is in progress. If we can find a decent way to present this then I'll see about getting it into the next release. Thanks for the feedback!

**Comment by jamesrward** [comment]
Kicking right into the pulsing V used to animate the refresh would probably be enough feedback for me.  If we need something more explicit perhaps overlaying the V with the play triangle icon used for Vagrant Up would solve the problem with an existing asset.

**Comment by TheLalaMan** [comment]
+1

**Comment by mojo2012** [comment]
+1

**Comment by chriswayoub** [comment]
This issue has been resolved in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
