### ISSUE TITLE
Vagrant keeps requesting SU password

### ISSUE THREAD

**Issue by Dragooon** [lanayotech/vagrant-manager#143]
Hello! Awesome software there. I just have a little issue, I'm using a plugin for vagrant which automatically takes care of my hosts file and it requires su password which is okay but when I run the same command through Vagrant, it requests it at least 6 times before the machine runs. Is there a way to fix this?

**Comment by jjanusch** [comment]
I've had this problem since upgrading to Sierra. Each time I up a machine through Vagrant Manager, it requests my password 4-6 times. If I do it through CLI, it only asks once.

**Comment by chriswayoub** [comment]
I'm seeing this issue on Sierra as well. It looks like Vagrant actually runs 4 sudo commands when configuring NFS, so it's prompting 4 times. The terminal remembers your sudo password for a short while, so it only prompts you once, but the same is not happening in the NSTask in Vagrant Manager for some reason. I haven't come up with any solution within Vagrant Manager itself yet, but this sudoers adjustment stopped it from prompting me multiple times:

http://stackoverflow.com/questions/39474047/sudo-command-on-macos-sierra-does-not-respect-timestamp-timeout

**Comment by jjanusch** [comment]
I can confirm that the method mentioned by @chriswayoub does suppress the password prompts. I don't know of a way to fix it in Vagrant Manager, however.

**Comment by stevieg83** [comment]
seeing this issue as well :( such a pain

**Comment by bensquire** [comment]
Same here!

**Comment by andrew40** [comment]
fixed using @chriswayoub solution above. and relax . . .

**Comment by joshlopes** [comment]
As anyone found a solution for this ?

**Comment by wireblue** [comment]
Bump. Also looking for a proper solution.

Disabling tty_tickets doesn't look like a good idea.

**Comment by aberonni** [comment]
Any updates on this? I'm encountering the same issue on macOS Sierra.

**Comment by acrosman** [comment]
Looks like there are solutions to this through the [Authorization Services Programming Guide](https://developer.apple.com/library/content/documentation/Security/Conceptual/authorization_concepts/01introduction/introduction.html) but they are somewhat involved. Looks like getting NSTask to play nicely with privilege escalation is intentionally hard to force people to do it "right".

**Comment by acrosman** [comment]
Looks like there may be a vagrant/sudo work around if you are willing to allow an escalation without a password entirely: https://askubuntu.com/a/519841 (I have not tried this myself, but seems likely to bypass this issue).

**Comment by runofthemill** [comment]
one of the other answers in the thread linked to by @acrosman worked for me (macOS 10.12.6) (https://askubuntu.com/a/945423)

the short of it is running this command:
`sudo chmod +a "$USER allow write,append" /etc/hosts`

this opens up some security risks, but if you know what's writing to `/etc/hosts` it may be something you're comfortable with

**Comment by chriswayoub** [comment]
I don't think there is a good way to resolve this on our end. The "right" way would be to use privilege escalation, but in that case it's going to ask you for your password every single time regardless of whether or not it needs it for the command it is running, and I don't think that's convenient at all. There isn't a great way for us to know whether or not the command you are running actually requires privilege escalation beforehand. I think the best solution is the one mentioned in the [Vagrant docs](https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement). Sorry for this inconvenient behavior, if anyone has a good solution then we can re-open this issue.
