### ISSUE TITLE
/bin/bash: shell_session_update: command not found

### ISSUE THREAD

**Issue by runofthemill** [lanayotech/vagrant-manager#145]
Hey there - this appears to be a non-critical bug as the actual command (`vagrant up`) ran fine, but the task window shows the following at the end:

`/bin/bash: shell_session_update: command not found`

My `Terminal Preference` is set to `iTerm/iTerm2`, but my login shell (and iTerm2 default) is zsh.

Using Vagrant Manager v 2.5.4

**Comment by chriswayoub** [comment]
That looks like it might be unrelated to Vagrant Manager. Can you take a look at the recommendations here and see if it resolves your issue?

http://superuser.com/questions/1044130/why-am-i-having-how-can-i-fix-this-error-shell-session-update-command-not-f

**Comment by runofthemill** [comment]
Running `rvm get head` fixed the issue, but my intuition tells me this is still related to Vagrant Manager, as I have never received the notice when running any Vagrant commands in my terminal. Does Vagrant Manager not use the login shell, or use Ruby?

Thanks for pointing me in the right direction!
