### ISSUE TITLE
How to run vagrant-manager after git clone?

### ISSUE THREAD

**Issue by scheung38** [lanayotech/vagrant-manager#148]
Mac OSX

Thanks

**Comment by jackrsteiner** [comment]
I think this questions is actually trying to ask, "If a directory already contains a Vagrantfile, how do I add it to the vagrant-manager menu?"

The machine listings are called bookmarks by vagrant-manager. If you select "Manage Bookmarks" and add the directory that contains the Vagrantfile via the sub-menu, the machine will appear in the vagrant-manager menu.
