### ISSUE TITLE
FEATURE REQUEST: Run a Vagrant command on startup

### ISSUE THREAD

**Issue by ecbrodie** [lanayotech/vagrant-manager#151]
It would be a neat feature if vagrant-manager could support running a vagrant machine command on system startup. This would replace me having to write a launchctl .plist file to execute `vagrant up` on startup. While that solution works, I would prefer to set it up in a user-friendly GUI like vagrant-manager.

**Comment by MatheusRV** [comment]
+1

**Comment by ecbrodie** [comment]
@amitailanciano @chriswayoub any update on this? It would be an amazing addition to this application. Thank you.

**Comment by chriswayoub** [comment]
This issue has been resolved in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
