### ISSUE TITLE
Any plan for a linux fork?

### ISSUE THREAD

**Issue by GabLeRoux** [lanayotech/vagrant-manager#154]
I was on MacOS before and enjoyed this nice tool, I'm now on [Archlinux](https://www.archlinux.org/) and I wish I had a similar tool. 

I manage vms from virtualbox with their strange names instead.

Using [electron](http://electron.atom.io/), it's quite easy to get a tray menu on arch using the following documentation:
http://electron.atom.io/docs/api/tray/

![image](https://cloud.githubusercontent.com/assets/1264761/21651152/8ad5bde8-d275-11e6-8e1a-77b26edcb04e.png)

Not quite sure which technology should be used and I haven't looked at the code in the current repository. All I know is that you went the native path (which is cool) ;)

**Comment by GabLeRoux** [comment]
I just found the following inspired repository that uses electron:
https://github.com/vaibhav-sidapara/vagrant-manager

Not working as expected for me yet, but it's on the right way :)

**Comment by amitailanciano** [comment]
no plans at the moment, sorry :( We'll link it on the README if we ever put one out though
