### ISSUE TITLE
OS X, Vagrant Up error

### ISSUE THREAD

**Issue by Webfenix** [lanayotech/vagrant-manager#157]
Hello,
When I use **Vagrant Manager** to start machine, it fails with errors - https://pastebin.com/sYYzpkds
I tried to rename config folder because it contain some specific characters, but it didn't change situation.
Thanks.

**Comment by amitailanciano** [comment]
Does it work when you try to up from the command line?

**Comment by Webfenix** [comment]
Yes, it does.

**Comment by amitailanciano** [comment]
Are you able to post the lines in your Vagrantfile relevant to that plugin?

**Comment by Webfenix** [comment]
Oops, I have specific characters in my **Vagrantfile**.. ;)
There were in synced folders path.
