### ISSUE TITLE
Detected Provider is wrong

### ISSUE THREAD

**Issue by stephenreay** [lanayotech/vagrant-manager#160]
The selected "Provider" value in the menu seems to be based on the presence of directories under `.vagrant/machines/$MachineName`

e.g. I have a client project, where I nominally use Parallels. In the past I had destroyed the Parallels box, re-created it using the VirtualBox provider (to debug/resolve an issue another dev had related to VB), and then reversed, destroying the VB provider machine and creating the Parallels one.

This left an empty `virtualbox` directory in the path mentioned above, which caused Vagrant Manager to show the provider as virtualbox.

Maybe instead of checking for a directory, check for the file, `.vagrant/machines/$MachineName/$provider/id`

**Comment by chriswayoub** [comment]
This issue has been resolved in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
