### ISSUE TITLE
How to completely remove this app?

### ISSUE THREAD

**Issue by korobochkin** [lanayotech/vagrant-manager#161]
After trying this app I decide using Vagrant only via terminal commands and I'm looking for manual how to fully remove app and all of its parts (logs, configs...).

**Comment by chriswayoub** [comment]
I used [AppCleaner](http://freemacsoft.net/appcleaner/) to find a list of files on my machine. Some of these may not apply to you:

- /Applications/Vagrant Manager.app
- ~/Library/Application Support/CrashReporter/Vagrant Manager*
- ~/Library/Caches/lanayo.Vagrant-Manager

**Comment by korobochkin** [comment]
Thank you! Seems like all developers forget about uninstall functionality =)

**Comment by daylightbrightledlight** [comment]
These files could be added to https://github.com/caskroom/homebrew-cask/blob/master/Casks/vagrant-manager.rb
