### ISSUE TITLE
Virtualbox 5.2 causes termination due to uncaught exception 'NSRangeException'

### ISSUE THREAD

**Issue by techaddicted** [lanayotech/vagrant-manager#162]
Upgrading Virtualbox to 5.2 causes Vagrant Manager to crash with:
> Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringToIndex:]: Index 1 out of bounds; string length 0'

**Versions**
macOS: 10.13 (17A405)
Vagrant: 2.0.0
Vagrant-Manager: 2.5.4
Virtualbox: 5.2.0r118431
Steps to recreate:
- Install Vagrant
- Install Virutalbox 5.2
- Open Vagrant Manager (Status icon appears and crashes after 1 to 2 seconds) 

Full error log from Xcode:
`2017-10-20 17:45:17.667793+0200 Vagrant Manager[18822:268122] [General] An uncaught exception was raised
2017-10-20 17:45:17.667848+0200 Vagrant Manager[18822:268122] [General] *** -[__NSCFConstantString substringToIndex:]: Index 1 out of bounds; string length 0
2017-10-20 17:45:17.667978+0200 Vagrant Manager[18822:268122] [General] (
	0   CoreFoundation                      0x00007fff2ccce0fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff53962c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2cd5fbfd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff2eceafd1 -[NSString substringToIndex:] + 118
	4   Vagrant Manager                     0x00000001000257ac +[VirtualBoxMachineInfo initWithInfo:] + 1116
	5   Vagrant Manager                     0x00000001000250a7 -[VirtualBoxServiceProvider getVirtualMachineInfoFromUUID:] + 727
	6   Vagrant Manager                     0x00000001000243b0 -[VirtualBoxServiceProvider getVagrantInstancePaths] + 400
	7   Vagrant Manager                     0x00000001000133d5 -[VagrantManager detectInstancePaths] + 421
	8   Vagrant Manager                     0x0000000100011b2a -[VagrantManager refreshInstances] + 2426
	9   Vagrant Manager                     0x0000000100008605 __37-[AppDelegate refreshVagrantMachines]_block_invoke + 53
	10  libdispatch.dylib                   0x00000001003fee3e _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00000001003f6f1f _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000100404da4 _dispatch_queue_override_invoke + 1387
	13  libdispatch.dylib                   0x00000001003f8d77 _dispatch_root_queue_drain + 723
	14  libdispatch.dylib                   0x00000001003f8a50 _dispatch_worker_thread3 + 116
	15  libsystem_pthread.dylib             0x00000001004731d2 _pthread_wqthread + 1387
	16  libsystem_pthread.dylib             0x0000000100472c55 start_wqthread + 13
)
2017-10-20 17:45:17.668887+0200 Vagrant Manager[18822:268122] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringToIndex:]: Index 1 out of bounds; string length 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2ccce0fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff53962c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2cd5fbfd +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff2eceafd1 -[NSString substringToIndex:] + 118
	4   Vagrant Manager                     0x00000001000257ac +[VirtualBoxMachineInfo initWithInfo:] + 1116
	5   Vagrant Manager                     0x00000001000250a7 -[VirtualBoxServiceProvider getVirtualMachineInfoFromUUID:] + 727
	6   Vagrant Manager                     0x00000001000243b0 -[VirtualBoxServiceProvider getVagrantInstancePaths] + 400
	7   Vagrant Manager                     0x00000001000133d5 -[VagrantManager detectInstancePaths] + 421
	8   Vagrant Manager                     0x0000000100011b2a -[VagrantManager refreshInstances] + 2426
	9   Vagrant Manager                     0x0000000100008605 __37-[AppDelegate refreshVagrantMachines]_block_invoke + 53
	10  libdispatch.dylib                   0x00000001003fee3e _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00000001003f6f1f _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x0000000100404da4 _dispatch_queue_override_invoke + 1387
	13  libdispatch.dylib                   0x00000001003f8d77 _dispatch_root_queue_drain + 723
	14  libdispatch.dylib                   0x00000001003f8a50 _dispatch_worker_thread3 + 116
	15  libsystem_pthread.dylib             0x00000001004731d2 _pthread_wqthread + 1387
	16  libsystem_pthread.dylib             0x0000000100472c55 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by ngocphamm** [comment]
Maybe due to the fact that Vagrant 2.0.0 (latest, as of now) does not support VB 5.2 yet.

**Comment by techaddicted** [comment]
Could be, but I patched vagrant my self to support VB 5.2...

I'll keep this issue open until vagrant with VB 5.2 support will be released

**Comment by chriswayoub** [comment]
We'll look into this. At the very least it shouldn't crash if it gets an unexpected value from the vagrant command.

**Comment by pawitp** [comment]
FYI, Vagrant 2.0.1 has been released with VirtualBox 5.2.0 support and Vagrant Manager is still crashing with the same error.

**Comment by mdavis1982** [comment]
I'm also having this issue... Vagrant Manager would boot - as soon as I added a machine to VirtualBox 5.2, it crashes immediately on startup.

Is there any progress on this at all? :smile:

**Comment by chriswayoub** [comment]
This has been resolved and we're putting together a new release that addresses this along with other issues that have been reported (and some features that have been requested).

**Comment by chriswayoub** [comment]
This issue has been resolved in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
