### ISSUE TITLE
Hide Dock Icon

### ISSUE THREAD

**Issue by mdavis1982** [lanayotech/vagrant-manager#163]
Is there a way of hiding the dock icon?

I swear before upgrading to High Sierra the dock icon wasn't showing - but it is now and I don't see any options to hide the dock icon.

Is this possible?

**Comment by chriswayoub** [comment]
Do you have the "Halt machines on exit" option enabled in your preferences?

**Comment by mdavis1982** [comment]
@chriswayoub I do. Turning that option off hides the dock icon. Is it not possible to have my cake and eat it as well? 🍰 😄

**Comment by ryanaltvater** [comment]
Just ran into this myself. I think it would be nice to not have the icon displayed in the dock at all, or at least an sub-option of hiding the dock icon if the "Halt machines on exit" option is enabled.

**Comment by chriswayoub** [comment]
Unfortunately, we can't hide the dock icon if "halt on exit" is enabled or the system won't wait on Vagrant Manager when it's shutting down. OS X doesn't let background apps pause the shutdown process to finish what they were doing, it just force kills the process.
