### ISSUE TITLE
Add micro to editor list

### ISSUE THREAD

**Issue by fbnlsr** [lanayotech/vagrant-manager#166]
It would be nice if we could use [micro](https://micro-editor.github.io/) as terminal editor.

Also maybe add an option to use the terminal editor to edit the Vagrant file?

**Comment by chriswayoub** [comment]
Yeah, we can add an option for micro in the next release

**Comment by amitailanciano** [comment]
this will be included in the next release, we may add the ability to use the terminal editor to edit the vagrant file in the future
