### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by olimortimer** [lanayotech/vagrant-manager#167]
Hi,

I've installed, uninstalled and reinstalled Vagrant Manager a number of times now, but it just shows that it's loading and never picks up any running Vagrant boxes.  I can't seem to find any log files to debug it either.

Any ideas?

It's the same when I download the dmg and install via brew.

**Comment by olimortimer** [comment]
I've left it for a couple of days now, and all it's showing is 'Refreshing...' rather than any boxes.

**Comment by chriswayoub** [comment]
Sorry you're having trouble...

Could you let me know your versions of:
* Vagrant
* VirtualBox
* Vagrant Manager

Also the values in your Preferences and the output of "vagrant global-status" from the command line? Do you have the `Use Provider Machine Detection` option checked in Preferences, and does that seem to make any difference?

**Comment by olimortimer** [comment]
I believe I'm running the latest version of each:

* Vagrant 2.0.3
* Virtualbox 5.2.8-121009
* Vagrant Manager 2.6.0

Here's the output of `vagrant global-status`, with names redacted:

`id       name                provider   state    directory
----------------------------------------------------------------------------------------------------
f6bc1cb  default             virtualbox poweroff /Users/olimortimer/Sites/abc.co.uk
f722a24  default             virtualbox poweroff /Users/olimortimer/Sites/def.co.uk
4fe4d9d  ghi virtualbox poweroff /Users/olimortimer/Sites/ghi
6baf2a6  default             virtualbox poweroff /Users/olimortimer/Sites/jkl.co.uk
2cec0ab  default             virtualbox poweroff /Users/olimortimer/Sites/mno.co.uk
96e9013  pqr         virtualbox poweroff /Users/olimortimer/Sites/pqr
71a9c9b  stu      virtualbox unknown  /Users/olimortimer/Sites/stu.co.uk
5ff8595  default             virtualbox poweroff /Users/olimortimer/Sites/vwx.co.uk
49d8d36  default             virtualbox aborted  /Users/olimortimer/Sites/yz.co.uk`

All preferences are the default from install, ie everything unchecked.

Checking `Use Provider Machine Detection` doesn't seem to make any difference.

**Comment by artursmirnov** [comment]
Same for me, always refreshing.

- Windows 10 latest (1709)
- Vagrant 2.0.2
- Virtualbox 5.2.8 r121009
- Vagrant Manager 1.0.0.6

```
> vagrant global-status
id       name    provider   state    directory
-------------------------------------------------------------------------
506e584  default virtualbox poweroff S:/vagrant
```

**Comment by amitailanciano** [comment]
We were unable to recreate this, but it may have been fixed by some other changes in the next release.

Please re-open if any of you are still experiencing issues after testing the latest release.

**Comment by olimortimer** [comment]
Showing now, thank you
