### ISSUE TITLE
Hyper.is not available as a terminal option

### ISSUE THREAD

**Issue by anakinjay** [lanayotech/vagrant-manager#169]
Small request, but I swear by hyper.  Would be awesome to be able to select it as the default in vagrant manager.

https://hyper.is/

**Comment by ngocphamm** [comment]
This is not related at all but I looked at Hyper the other day and gave it a brief try but can you tell me what's the main advantages of using it over something else, say iTerm, or Terminal?

**Comment by anakinjay** [comment]
> This is not related at all but I looked at Hyper the other day and gave it a brief try but can you tell me what's the main advantages of using it over something else, say iTerm, or Terminal?

It's a purely html / js based terminal running in (I believe) electron.  So if you're like me and work all day on your mac, go home and sometimes need to have to do work from your windows machine, and like to catch up on some stuff on your ubuntu laptop, the experience is exactly the same across all platforms.

It also makes it easily extensible and has lots of really awesome plugins:
https://github.com/bnb/awesome-hyper

**Comment by anakinjay** [comment]
I mean look at this... you can have a rocket ship take off every time you push a git commit.  UNLIMITED POWER :P

https://www.npmjs.com/package/gitrocket

**Comment by ngocphamm** [comment]
Oh so it's about cross-platform experiences for you. Totally legit! I mainly use mac, and have already gave up in using command line in Windows, so for me iTerms is just enough. Thanks for the info!!!

**Comment by claudiosv** [comment]
@anakinjay 
I've submitted a [pull request](https://github.com/lanayotech/vagrant-manager/pull/171) to add this feature, if the maintainer accepts it, you'll be able to use Hyper.

**Comment by amitailanciano** [comment]
this will be included in the next release -- thanks!
