### ISSUE TITLE
Confirm Popup to front

### ISSUE THREAD

**Issue by DonRichards** [lanayotech/vagrant-manager#170]
## The confirm popup doesn't always appear in front of running apps. 

The only way to see it if to minimize all apps on top of the confirmation. This makes finding it a bit difficult when using multiple screens. Although more often than not it is somewhere on the 1st screen it still isn't easily found. 

### To replicate issue
* Use vagrant manager to do a "vagrant destroy"
* start using an app that covers the center of your screen while waiting for app to open.

**Comment by amitailanciano** [comment]
this should be fixed in the next release
