### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by amitailanciano** [lanayotech/vagrant-manager#174]
Add support for dark mode

<img width="467" alt="screen shot 2019-02-06 at 2 48 45 pm" src="https://user-images.githubusercontent.com/1289466/52376018-52ea8f00-2a1e-11e9-91db-20c57afad504.png">

**Comment by fa2mm** [comment]
The content is the same color as the background.

<img width="806" alt="screen shot 2019-02-12 at 10 05 32" src="https://user-images.githubusercontent.com/3799461/52620715-02f04a00-2eae-11e9-843e-690588aa5675.png">

**Comment by dasginganinja** [comment]
https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface/

**Comment by chriswayoub** [comment]
Dark Mode is now support as of 2.7.1
