### ISSUE TITLE
Option to hide dock icon?

### ISSUE THREAD

**Issue by damienmckenna** [lanayotech/vagrant-manager#177]
I'm not sure if it was updating to Mojave or updating the program, but until recently the dock icon used to be always disabled or hidden. The current release on Mojave does not have a way of changing that, so the dock icon always shows. Was this an intentional change or did something change in macOS that causes the dock icon to always be present? Thank you.

**Comment by chriswayoub** [comment]
If you disable the `Halt machines on exit` option in the preferences then you should only see the dock icon when a Vagrant Manager window is open. Unfortunately, we haven't found a way to hide the dock icon and also enable the functionality to pause system shutdown to wait for the machines to halt.

Let me know if turning that option off doesn't work for you and I'll re-open this issue!

**Comment by damienmckenna** [comment]
Ah! That works, thank you.

It might be worth adding a comment in the preferences UI that explains this.
