### ISSUE TITLE
CPU intensive

### ISSUE THREAD

**Issue by kostaspt** [lanayotech/vagrant-manager#18]
For some reason, after updating from v1.3.3.b1 to v1.5.2, it started using way too much CPU power. So now I have to close it, when I'm not using it. Any ideas why is this happening?

![Screenshot](http://cl.ly/image/0R1U09432v0g/Screen%20Shot%202014-05-27%20at%201.24.23.png)

I have 2 vm machines, 1 running and 1 powered off. The one running is this one: http://laravel.com/docs/homestead

**Comment by travisdetert** [comment]
I can verify that version 2.2.1 still has issues.  To reproduce the problem, enabling the animated icon on yosemite pegs cpu usage overall at 100%, I suspect it has to do with the windowserver actually rendering the animated icon constantly and the transparency has to have something to do with it.

1). Set refresh to 5 seconds
2). Enable animated icon
3). Watch activity monitor cpu activity go to 100% within minute or less.

4). Disable animated icon, cpu goes back to normal.
