### ISSUE TITLE
Python quit unexpectedly

### ISSUE THREAD

**Issue by robrecord** [lanayotech/vagrant-manager#181]
I get this crash report appearing on my screen multiple times per day; yesterday and today. It looks like Vagrant Manager is responsible.
Let me know if you need more details.

```
Process:               Python [3193]
Path:                  /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.7.5 (3.7.5)
Code Type:             X86-64 (Native)
Parent Process:        ruby [3156]
Responsible:           Vagrant Manager [1869]
User ID:               501
```

The rest of the log is here:
https://gist.github.com/robrecord/5c01dcf2414b233f33347c859b9f8adf

**Comment by robrecord** [comment]
Still happening 4 days later.

**Comment by amitailanciano** [comment]
Hi Rob,

Vagrant Manager doesn't run any python scripts, but it does use the [NSTask API to execute](https://github.com/lanayotech/vagrant-manager/blob/develop/Vagrant%20Manager/AppDelegate.m#L500) `vagrant` commands. If I had to guess, I'd wager you'd encounter the same error executing the problematic command(s) from the command line?

Perhaps [this StackOverflow post](https://stackoverflow.com/questions/58272830/python-crashing-on-macos-10-15-beta-19a582a-with-usr-lib-libcrypto-dylib) can help resolve your specific issue, it looks like it may be related to your homebrew python3 installation and macOS Catalina.

**Comment by robrecord** [comment]
Thanks @amitailanciano - I used this particular answer with a few modifications: https://stackoverflow.com/a/59221089/445547

I am using trellis by roots, and trellis-cli, which installs a python environment. Here's what I did for my scenario:

```bash
rm -r /usr/local/lib/python*/site-packages/asn1crypto*
rm -r trellis/.trellis/virtualenv
trellis init # recreates a python environment and installs dependencies with pip
```

For other software see the answer which reinstalls the pip dependencies manually.
