### ISSUE TITLE
Out of Disk Space On Website

### ISSUE THREAD

**Issue by n0nag0n** [lanayotech/vagrant-manager#190]
In case you're wondering, your public webpage has an error on the bottom which is affecting the ability to use the contact us form.

![image](https://user-images.githubusercontent.com/2322095/179031521-fe779e90-795b-4811-9836-7c7688e23bda.png)

```
Warning: Unknown: open(/home/lanayo/tmp/php/session/sess_bmk80vm9kgbrlqihsmqku0jk86, O_RDWR) failed: No space left on device (28) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/home/lanayo/tmp/php/session) in Unknown on line 0
```

**Comment by amitailanciano** [comment]
Thank you for the heads up!
