### ISSUE TITLE
Supporting Vagrant SSH other than bash

### ISSUE THREAD

**Issue by daniel-choi** [lanayotech/vagrant-manager#20]
It would be great to customize the vagrant ssh command. I have a fish shell and vagrant ssh command doesn't work on the fish shell. (`;` or `and` instead of `&&`) 
![image](https://cloud.githubusercontent.com/assets/2504659/3133861/dd1cddbe-e81e-11e3-9bcf-eba97b9eb326.png)

**Comment by FezVrasta** [comment]
I've the same problem, how can I fix it?

**Comment by danmatthews** [comment]
@FezVrasta what Shell are you using? I submitted a pull for this that should have covered the majority of cases. 

Also, are you running the latest version?

**Comment by FezVrasta** [comment]
I'm on the latest version and I'm using the default Yosemite terminal with Fish

**Comment by daniel-choi** [comment]
Are you running the latest version of vm?
I am using Yosemite terminal with Fish as well and it works fine on my mac.

**Comment by FezVrasta** [comment]
The auto update tool says I'm on the newest version.

**Comment by daniel-choi** [comment]
What's the error message?

**Comment by FezVrasta** [comment]
````````bash
\cd '/Users/fezvrasta/Progetti/project-folder'; vagrant ssh
fish: Unknown command ''
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
``````

**Comment by danmatthews** [comment]
Looks like it's running the command fine, but it may be in the wrong directory.

Have you tried manually doing `cd /Users/fezvrasta/Progetti/project-folder`, then `vagrant ssh` ?

**Comment by FezVrasta** [comment]
yes if I write commands manually everything works. Looks like the `cd` command fails when ran from vagrant manager

**Comment by daniel-choi** [comment]
https://github.com/lanayotech/vagrant-manager/commit/c1e0a11905afecb12a29fb308f70bd25c9095ed5#diff-1e80cab3d8dade4bad5e7fa93572716eR346

I think this update breaks the command. I just updated my vagrant manager and I am getting the same error. "\" is included in front of the command. `\cd '/Users/...'; vagrant ssh
