### ISSUE TITLE
Machine Names

### ISSUE THREAD

**Issue by williamekwhite** [lanayotech/vagrant-manager#38]
Now in version 2, the names for my machines are showing up based on the folder directory of the vagrant config files NOT the name of the machine.

Good there be an option to select the interface machine label by machine name OR by vagrant directory?
![screen shot 2014-10-01 at 9 14 59 am](https://cloud.githubusercontent.com/assets/7243286/4476352/685e4180-4975-11e4-9ed4-413f5f909639.png)

**Comment by gmhenderson** [comment]
+1 displaying box name would be great.
