### ISSUE TITLE
File Edit (Conf/Logs) from the app

### ISSUE THREAD

**Issue by chenasraf** [lanayotech/vagrant-manager#45]
I'd love a possibility of a quick way to reach the logs, configs and other files in a (perhaps configurable?) list for easy access. The way we have to do it now is either go to ssh, and open a command line editor, or find a way to sync the files with one on our system, which can be a bit of a hassle. It'd be great if we could pick a file, open it in our favorite editor, and once saved, sync it back to the machine!

**Comment by chriswayoub** [comment]
Version 2.2.0 adds Custom Commands, which lets you execute shell commands on the Vagrant machine over SSH. With this, you can add a command such as "vim /etc/hosts" and check the "Run in Terminal" checkbox to edit the Vagrant machine's /etc/hosts file. We may revisit this at a future date to expand this functionality.
