### ISSUE TITLE
Bookmark scripts

### ISSUE THREAD

**Issue by BogdanHabic** [lanayotech/vagrant-manager#51]
It would be great if there was a feature to define custom scripts and run them on the VMs. So lets say for example i want to rerun all migrations on a VM: what I would do usually is ssh into the machine and do something like this:
"cd Code/project_name_here;php artisan migrate:refresh;"
I imagine this working in a way that you type out the commands, and save/bookmark them and then every VM has a submenu called "Bookmarked scripts" and then from there I select my custom "Rerun migrations" script.
I would love to help you implementing this, but I don't promise anything because I never developed something for OS X.

**Comment by chriswayoub** [comment]
Version 2.2.0 adds Custom Commands, which lets you execute shell commands on the Vagrant machine over SSH
