### ISSUE TITLE
Dealias cd command

### ISSUE THREAD

**Issue by Gerst20051** [lanayotech/vagrant-manager#52]
please update this to use \cd

**Comment by chriswayoub** [comment]
Vagrant Manager 2.2.0 now dealiases all instances of the cd command using a backslash.

**Comment by Gerst20051** [comment]
@chriswayoub do you have a link to the commit?

**Comment by Gerst20051** [comment]
@chriswayoub found it. thanks! https://github.com/lanayotech/vagrant-manager/commit/165c40d2320aed51f6cc1b7aa1fa99f853a9c0f1
