### ISSUE TITLE
Feature: vagrant ssh -c 'bla bla' and vagrant ssh with arguments

### ISSUE THREAD

**Issue by seromenho** [lanayotech/vagrant-manager#56]
Could this be a cool thing. Have the feature of add custom commands that we often use and arguments to ssh.
Use the -c option to run a command or vagrant ssh with arguments.
Samples
vagrant ssh -c 'sudo service memcached restart'
or 
vagrant ssh -- -t 'cd /var/local/www && exec $SHELL'

What do you thing?

**Comment by rarkins** [comment]
This is a great idea. I'd like to avoid needing people to open `vagrant ssh` for typical daily routines.

**Comment by chriswayoub** [comment]
Version 2.2.0 adds Custom Commands, which lets you execute shell commands on the Vagrant machine over SSH

**Comment by seromenho** [comment]
Yey! Thanks :thumbsup:
It would also be great to ssh with arguments.
