### ISSUE TITLE
$VAGRANT_HOME not respected

### ISSUE THREAD

**Issue by Dbzman** [lanayotech/vagrant-manager#58]
On our setup with the users home folder on a network (active directory) it is required to move the "vagrant.d" folder out of the users home directory by setting $VAGRANT_HOME in for example ".bashrc" or ".bash_profile".
Sadly there is no obvious way to set that variable for vagrant manager as it does not seem to respect settings made in one of the above mentioned files.
Is there a way to do that? It would be great if vagrant manager could read the users bash settings.

**Comment by chriswayoub** [comment]
Version 2.2.0 now executes bash as a login shell, which should respect your .bash_profile
