### ISSUE TITLE
Suggestion - Icon Animation Setting

### ISSUE THREAD

**Issue by noeldiaz** [lanayotech/vagrant-manager#59]
Just a suggestion for your consideration.  Would it be possible to add another option icon to disable the icon animation on the toolbar when it refreshed to get vagrant machine information?  I understand its usefulness but it is very distracting when you have the refresh time low.  Would be awesome to have a choice on it.  Thank you for the great program!

**Comment by chriswayoub** [comment]
Version 2.2.0 adds a preference to disable the icon animation.
