### ISSUE TITLE
Boxes are never recognized as up

### ISSUE THREAD

**Issue by ramondelafuente** [lanayotech/vagrant-manager#6]
I installed Vagant Manager, and added a bookmark manually. I can see the box in the list, I can run the `up` command, I get the command output in the window and the box is started.  But the box is never seen as `running` in Vagrant Manager.

Also, the `details` for the box are all _N/A_

I read in the docs that: _Currently, vagrant machines must already be initialized in order for Vagrant Manager to detect them._, but that is followed by _You can also manually add a bookmark and specify the path to your Vagrantfile_ so I assume my box should be working.

My versions:
- OSX 10.9.2
- Vagrant 1.6.1
- Virtualbox 4.3.10

**Comment by bhanu-prakashl** [comment]
i have the issue like this below and vagrant up doesn't work....
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.

is there any version compatibility issues ?
