### ISSUE TITLE
Feature: Process Windows always on top

### ISSUE THREAD

**Issue by jwhitcraft** [lanayotech/vagrant-manager#60]
It would be awesome if there was an option to alway have the Process windows stay on top.  Currently it's hard to keep track of the windows cause there is no way to cmd+tab back to them to see if they are still up.

**Comment by amitailanciano** [comment]
I agree, I believe we actually had this feature in an earlier version; we'll add it back in

Thanks for the suggestion

**Comment by chriswayoub** [comment]
Version 2.2.0 adds back in the "Window" menu to show all open windows.
