### ISSUE TITLE
Crashes with new 2.2.0 release

### ISSUE THREAD

**Issue by ngocphamm** [lanayotech/vagrant-manager#62]
I don't know if this is actually a problem with the new release, but I've got 2 crashes so far. I don't think I got one before.

The first time is when I tried `vagrant up` a box. It started the machine okay, but then crash. The second time I didn't even notice until a few mins ago when I looked at the menu bar and didn't see the icon there.

This is the crash log: http://pastebin.com/wpLd5SnE

OS: Yosemite 10.10.1
Vagrant: 1.7.1
Vagrant Manager: 2.2.0

I hope this is a bug and can be squashed.

Thank you!

**Comment by chriswayoub** [comment]
We are currently investigating this issue. We have had several reports of this happening, and have noticed it ourselves as well. I think we've tracked it down and can hopefully release a fix tonight.

**Comment by ngocphamm** [comment]
Thanks, @chriswayoub. I didn't see the crash report window to submit the log, so I thought it'd probably nice to file an issue here.

**Comment by chriswayoub** [comment]
Release 2.2.1 should resolve this issue.
