### ISSUE TITLE
Notification Center Integration

### ISSUE THREAD

**Issue by apocalyptic0n3** [lanayotech/vagrant-manager#65]
I'd like to suggest integrating Vagrant Manager with Notification Center. Currently, the status windows get lost behind other windows and, depending on settings, can be hidden as soon as they are complete. It'd be convenient if, on an up/reload/halt sequence (maybe others), it gave you a notification that the operation has completed.

**Comment by amitailanciano** [comment]
This has been implemented in [Release 2.3.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.3.0)
