### ISSUE TITLE
Fast auto-refresh causes performance drop on OS X 10.10.2

### ISSUE THREAD

**Issue by lookitsatravis** [lanayotech/vagrant-manager#67]
I am using the latest release as of this filing, 2.3.0, and on the latest Vagrant, 1.7.2. I set Auto-refresh to an interval of 5 seconds. After a few seconds, my fan is running at max, and my MacBook is fairly warm, so I jump into Activity Monitor and I see a process called `VboxSVC` running 19 threads using ~22% of the CPU, and the cpu usage time is ratcheting up like crazy.

There is another process which seems to be involved called `socketfilterfw` (Apple's Socket Firewall), and while that process is normally started on my box, when the refresh is happening, it too has a CPU spike up to about ~14% and is sustained as long as I have the 5 second refresh set.

I should also mention that those two processes spike also when the refresh is actually run, even on a longer auto-refresh. They also happen when I refresh manually. The difference is that the 5 second refresh makes the system more and more unusable.

**Comment by amitailanciano** [comment]
The refresh in general is a pretty intensive task, we scan for Vagrantfiles by examining paths in `/etc/exports`, parse the output of `vagrant global-status`, as well as query machine statuses using `VBoxManage` (and in the future, any other providers we will support). It is possible your system simply cannot keep up with that low of a refresh interval. The app queues up subsequent refreshes if it is already refreshing when a refresh is triggered, so that may explain why your system becomes gradually more sluggish, as the queue will continually increase if it cannot ever catch up. That said, perhaps the 5 second option should be removed

**Comment by lookitsatravis** [comment]
Thanks for the response. For what it's worth, I am running on a pretty beefy machine. 2014 MacBook Pro 2.5GHz i7 quad-core with HT, 16 gigs of RAM, and an SSD. Pretty much the top of the line MBP available today with the exception of one model that has a faster CPU. The only product that Apple sells with better specs is the Mac Pro, and I suppose that one shouldn't need an $4k machine to get decent refresh performance. This seems like a performance problem more to do with Virtual Box or Vagrant's performance than Vagrant Manager, but I wanted to draw attention to it in case there is something that can be done in this project. As you say, maybe a longer low-end refresh rate is in order and that's all there is to it. Thanks again!

**Comment by jbro** [comment]
It would be nice, if there was an option for using FSEvents and the `~/.vagrant.d/data/machine-index/index` for the box statuses. That would be very CPU saving.

**Comment by burriko** [comment]
Just to add to this, I've had an issue for the last couple of weeks where I'd experience typing lag in Sublime Text for a few seconds every now and then.  After much messing around disabling various Sublime packages I've now discovered that it was happening whenever Vagrant Manager was doing a refresh. I had the refresh interval set to every 15 minutes too, which I thought was fairly conservative.

Obviously the refresh is an intensive task, but would there be a way to run it at a very low priority using nice or something similar?  Or perhaps try to do less during an automated refresh? For instance, all I really want to achieve with the refresh is to know which VMs are running or not, and it would seem that a call to `vagrant global-status` should provide this information.

**Comment by grega** [comment]
I can echo @burriko's comment - I've had exactly the same lag whilst working in Sublime and it's definitely attributable to Vagrant Manager's refresh (6 VMs at 1 min interval). Issue #74 appears to be linked to this also and I see Yosemite consistently reporting high battery usage for Vagrant Manager (alongside Chrome) and Activity Monitor shows high levels of CPU usage for Vagrant Manager.

**Comment by cooperaj** [comment]
Found this after I hovered over my Battery on my early 2013 RMBP and discovered that VagrantManager is one of the apps using "Significant Energy" I've dropped my scan settings to 15mins in the hope that that eases off.

**Comment by amitailanciano** [comment]
@burriko `vagrant global-status` does not always show correct statuses, and the `--prune` flag to force it to do so is very slow. Not only that, but it might not show VM's you may still have in your exports file if you use NFS, while showing some that you don't.. so we just like to include it as another scanner to get the best of both.

I'm going to close this for now, perhaps @jbro 's comment is worth some investigation, or perhaps we'll add an option to allow you to choose or limit the scanners you want to use. We probably also only want to run `vagrant status` for machines we didn't match from the global status call. We'll work on reducing the scanning footprint in future releases.
