### ISSUE TITLE
Make the output window default to being at least 80 characters wide

### ISSUE THREAD

**Issue by ataylor32** [lanayotech/vagrant-manager#69]
Terminal defaults to being 80 characters wide and scripts often expect the window to be at least 80 characters wide. As an example of something that would benefit from this change, here is a screen shot of Terminal at the end of `vagrant up` with [PuPHPet](https://puphpet.com/):

![terminal](https://cloud.githubusercontent.com/assets/1054222/6149562/daa817a2-b1c6-11e4-9895-003da1184df8.png)

And here is the same thing in Vagrant Manager (I left the window alone; I didn't resize it):

![vagrant-manager](https://cloud.githubusercontent.com/assets/1054222/6149585/fd50f10c-b1c6-11e4-8548-d44eb57bf2af.png)

**Comment by amitailanciano** [comment]
Good suggestion, we'll change this for the next release

**Comment by amitailanciano** [comment]
implemented in [release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0)
