### ISSUE TITLE
Command + Tab cannot switch to task output windows.

### ISSUE THREAD

**Issue by EHLOVader** [lanayotech/vagrant-manager#70]
The task output windows aren't targetable with the command tab keyboard command. 

This leaves them lost behind windows on my machine usually and I have a hard time finding them.

on OSX 10.9.5 myself if that is a possible cause.

**Comment by amitailanciano** [comment]
This has been fixed and will be included in the next release, along with #71

**Comment by amitailanciano** [comment]
implemented in [release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0)
