### ISSUE TITLE
Task windows become hidden after password input

### ISSUE THREAD

**Issue by chenasraf** [lanayotech/vagrant-manager#71]
After I input my root password (for example when I Up my vagrant machine), the task window disappears and I have to use mission control to find it again.

**Comment by EHLOVader** [comment]
This is actually related to #70 

These windows aren't accessible after they leave the foreground. This is still a problem and I think it would be helpful to fix it.

Often provisioning may take awhile so I leave the window running, but getting back to it is harder than it should be.

**Comment by amitailanciano** [comment]
this has been fixed in [release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0)
