### ISSUE TITLE
Open in shell not working with fish

### ISSUE THREAD

**Issue by jbro** [lanayotech/vagrant-manager#72]
When pressing 'Open in Terminal' on a Vagrant box, vagrant-manager issues the command `\cd 'path\to\box'`. However when using fish as login shell, this does not work as intended, as fish does not support this syntax for bypassing an alias. 

A workaround is alias \cd to cd in fish: `alias \cd cd; funcsave \cd`.

It would be nice if an option was added to change the command issued for 'Open in Terminal', so the above workaround could be prevented.

**Comment by blazeworx** [comment]
+1 also experiencing this issue with fish shell

**Comment by doot0** [comment]
Recreatable on Yosemite 10.10.3. +1

**Comment by amitailanciano** [comment]
[release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0) should fix this issue

**Comment by Gerst20051** [comment]
@amitailanciano i like @jbro idea of making this an option in the preferences... it could be a toggle switch to dealias or not...
