### ISSUE TITLE
Showing duplicate machines with symlink and bad delete

### ISSUE THREAD

**Issue by jack-hs** [lanayotech/vagrant-manager#73]
So I have my machines in /Volumes/Case-Sensitive HD 2/vms/<machine name> and ~/vms is a symlink: vms -> /Volumes/Case-Sensitive HD 2/vms/

All the machines are showing once, except one. That one i didn't destroy, but i just deleted the whole machine folder (when it was halted) and deleted the vm in virtualbox. I then proceeded to create a brand new folder with the same name and a new vagrant in it.

Now it shows that i have 2 boxes one in ~/vms/<machine name> and second one in /Volumes/Case-Sensitive HD 2/vms/<machine name>. If i rename that folder both disappear, if i start it up, both are showing running, etc. Only 1 vm in virtualbox. All the other machines are just showing once.

Any clue on how to de-dup? (tried destroying and remaking, tried restarting everything).

**Comment by amitailanciano** [comment]
You migh try running `vagrant global-status --prune` to clean up invalid entries, also if you're using NFS, edit your `/etc/exports` folder and remove any invalid paths, hope that helps

**Comment by jack-hs** [comment]
Thank you!!!
running vagrant global-status --prune twice did it!
