### ISSUE TITLE
High power consumption under OSX

### ISSUE THREAD

**Issue by jancbeck** [lanayotech/vagrant-manager#74]
OSX activity monitor reports high average power consumption for vagrant manager. It's only rivaled by notorious apps such as Safari and Skype:

![bildschirmfoto 2015-02-23 um 22 10 32](https://cloud.githubusercontent.com/assets/865311/6342060/2a6c56e0-bba9-11e4-8f2a-9ce7a5474beb.png)

Can this be caused by the virtual machine running in the background? Or is vagrant manager itself actually causing the power drain?

**Comment by amitailanciano** [comment]
![screen shot 2015-03-26 at 3 52 16 pm](https://cloud.githubusercontent.com/assets/1289466/6858911/3b7e5e62-d3d0-11e4-8584-6e9a8787abf6.png)

Based on the process details, it appears Vagrant Manager itself is not responsible for the high power usage, it is mostly the aggregate consumption of active virtual machines.

**Comment by amitailanciano** [comment]
closing alongside #67

**Comment by jancbeck** [comment]
This might be an interesting read related to the issue:
[What does the OS X Activity Monitor’s “Energy Impact” actually measure?](https://blog.mozilla.org/nnethercote/2015/08/26/what-does-the-os-x-activity-monitors-energy-impact-actually-measure/)
One key takeaway from the article:
> In every case, Activity Monitor’s “Energy Impact” was the same as top‘s POWER measure. Every indication is that the two are computed identically on this machine.

When I check my top I usually see VBoxHeadless at position 1 or 2. @amitailanciano your observation is spot on!
