### ISSUE TITLE
Color Output / Console Codes

### ISSUE THREAD

**Issue by bbatsche** [lanayotech/vagrant-manager#75]
The output window echos console control characters to the screen. This is especially distracting if you use Ansible to provision a box. The result is a lot of:

```
[0;33mchanged: [vagrant][0m
```

when I'd expect to see:

```
changed: [vagrant]
```

Even without using Ansible, the start of the output always begins with:

```
]1337;RemoteHost=$USER@$HOST]1337;CurrentDir=/]1337;etc...
```

which is still pretty ugly.

**Comment by amitailanciano** [comment]
vagrant commands are now executed with `--no-color` in [release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0)

**Comment by bbatsche** [comment]
Just downloaded the latest version. I can see the `--no-color` flag being sent to the `vagrant` commands, but I'm still seeing a lot of console codes being displayed in the output. Are you sure `--no-color` is a valid Vagrant flag? My brief look at the documentation didn't list that as an option. I'm currently using Vagrant 1.7.2, which is the latest release near as I can tell.

**Comment by chriswayoub** [comment]
The --no-color option is [documented here](http://docs.vagrantup.com/v2/other/environmental-variables.html). If you run vagrant up with the --no-color option from the command line, does it still show those console codes? Or is it only in our task output window?

**Comment by bbatsche** [comment]
Did some additional testing with a second laptop (same version of Vagrant manager).

Running `vagrant up --no-color` turns off bold text and colors in both. Using Vagrant Manager in one displays console control characters while the other does not. So, could very well be an issue with my own set up. Not sure where to begin with debugging this, but I'll see what I can find. And thank you for the documentation link and humoring my question, I appreciate y'all's work and help. :sweat_smile:

Looking down the line however, it seems `--no-color` will not affect the output from Ansible at this point (there is currently a [pull request](https://github.com/mitchellh/vagrant/issues/5532) to address this, but it's not yet merged). Granted, dealing with colors from Ansible is probably Somebody Else's Problem, but still I wanted to bring up the issue.

**Comment by xenDE** [comment]
Now it's 2017 - far far into the future.

Can we now have Color Support? :)
