### ISSUE TITLE
LXC support

### ISSUE THREAD

**Issue by borgand** [lanayotech/vagrant-manager#77]
Is there a way to add LXC container support? I have a simple setup:
- A Linux VM (actually itself a Vagrant box, but that's irrelevant) that runs LXC
- My development folder is mounted via NFS to that box, so `.../projectX/Vagrantfile` appears local to the containerhost.
- (A shell alias that prefixes `vagrant` commands w/ relative SSH command. This step is optional, but allows a seamless usage as if LXC was supported on Mac OS X)

I'm not quite sure what is needed to interface with all the LXC boxes, but I'd  imagine a Preference for LXC container IP address or hostname would be a start. Then such a command would generate a list of Vagrant boxes:

```
% ssh containerhost "sudo bash -c 'grep -l VAGRANT-BEGIN /var/lib/lxc/*/config | cut -f5 -d/'"
projectx_default_1426516465190_1727
projecty_default_1426695430938_80868
```

After that `lxc-info` could be used to query the boxes:

```
% ssh containerhost "sudo lxc-info -n projectx_default_1426516465190_1727"
Name:           projectx_default_1426516465190_1727
State:          RUNNING
PID:            927
IP:             10.211.55.133
CPU use:        5962.76 seconds
BlkIO use:      737.65 MiB
Memory use:     410.26 MiB
KMem use:       0 bytes
```

Or other settings could be read directly from the `config` file, e.g. hostname and mount points:

```
lxc.utsname=projectx.vm
lxc.mount.entry=/sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry=/home/laas/prog/projectx srv/projectx none bind 0 0
```

Would it be possible to add this support?

PS. I think similar scheme would apply to `vagrant-docker` also.

**Comment by mrjcleaver** [comment]
+1 :)
