### ISSUE TITLE
Vagrant VMware Fusion Provider cannot clone boxes when Vagrant Manager is active

### ISSUE THREAD

**Issue by phinze** [lanayotech/vagrant-manager#78]
Hey folks,

Cool project! :)

I'm writing in because there seems to be an issue with Vagrant Manager and our VMware Fusion provider that breaks box cloning.

We've seen it a few times in our support queues. It seems to express itself as the box clone target showing up as a file when a directory is expected. The issue goes away when Vagrant Manager is disabled. I'm guessing it has to do with some sort of side effect of Vagrant Manager looking out for new machines?

Let me know if there are any other details I can provide that would be helpful - would be great to get this solved so people can use the VMware Fusion provider with Vagrant Manager installed.

**Comment by chriswayoub** [comment]
This is interesting... we don't do anything destructive when detecting machines. We check the output of vagrant global-status, use VBoxManager to query VirtualBox machines, prlctl to query Parallels machines, and check the /etc/exports file for any NFS mounts. We actually don't do anything specific to VMware, and none of the above should do anything to alter any files as far as I know. All we are doing is issuing the following command in bash:

> \\cd PATH_TO_VAGRANT_MACHINE; vagrant status

And then parsing the output. We do run all of our machine checks concurrently on different threads, could that be causing an issue? I can't really think of anything else off the top of my head.

I haven't used VMware myself, so I'll have to grab the trial and see if I can recreate this issue.

**Comment by grettke** [comment]
# Overview

Good evening,

Context: I was testing out my Vagrant installation on a new OS installation so
I tried running a box from Vagrant cloud. It didn't work. The box was downloaded.
The box appeared to have never started up though. It did start though. I could
vagrant ssh into it. Vagrant Manager also saw that it was running. When I turned
off Vagrant Manager, I did not run into that issue any more. Ultimately both
Vagrant and Vagrant Manager seemed to be working fine, but, having Vagrant
Manager installed caused a bug message to get generated.

Time: 2015-03-19T18:48:16-0500
OS:

    archey

                 ###
               ####                   User: gcr
               ###                    Hostname: orion
       #######    #######             Distro: OS X 10.9.5
     ######################           Kernel: Darwin
    #####################             Uptime: 8 hrs
    ####################              Shell: /bin/bash
    ####################              Terminal: dumb
    #####################             Packages: 68
     ######################           CPU: Intel Core i7-4960HQ CPU @ 2.60GHz
      ####################            Memory: 16 GB
        ################              Disk: 10%
         ####     #####

Vagrant:

    vagrant --version

    Vagrant 1.7.2

Vagrant Manager: 2.3.0

VMWare: Fusion Professional 7.1.1 (2498930)

Default provider:

    echo $VAGRANT_DEFAULT_PROVIDER=

    vmware_fusion=

# Steps to reproduce

    cd ~/tmp
    vagrant init chef/ubuntu-14.04
    vagrant up

    A `Vagrantfile` has been placed in this directory. You are now
    ready to `vagrant up` your first virtual environment! Please read
    the comments in the Vagrantfile as well as documentation on
    `vagrantup.com` for more information on using Vagrant.
    gcr@orion:~/tmp> vagrant up
    Bringing machine 'default' up with 'vmware_fusion' provider...
    ==> default: Box 'chef/ubuntu-14.04' could not be found. Attempting to find and install...
        default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
        default: Box Version: >= 0
    ==> default: Loading metadata for box 'chef/ubuntu-14.04'
        default: URL: https://atlas.hashicorp.com/chef/ubuntu-14.04
    ==> default: Adding box 'chef/ubuntu-14.04' (v1.0.0) for provider: vmware_desktop
        default: Downloading: https://atlas.hashicorp.com/chef/boxes/ubuntu-14.04/versions/1.0.0/providers/vmware_desktop.box
    ==> default: Successfully added box 'chef/ubuntu-14.04' (v1.0.0) for 'vmware_desktop'!
    ==> default: Cloning VMware VM: 'chef/ubuntu-14.04'. This can take some time...
    The clone directory given is not a directory. This is an internal
    error and should be reported as a bug to support@hashicorp.com.
    
    Path: /Users/gcr/tmp/.vagrant/machines/default/vmware_fusion/6f6dc52e-0f27-4349-9251-81c851367677
