### ISSUE TITLE
Option to use Vagrantfile name

### ISSUE THREAD

**Issue by Camoflame** [lanayotech/vagrant-manager#79]
Instead of using folder name for the Vagrant machine, would be great if there was an option (or by default) the Vagrant machine name would be the same as defined in the Vagrantfile config.

Example:
```
config.vm.provider "virtualbox" do |v|
  v.name = "my_vm"
end
```
Then the Vagrant machine name would appear as "my_vm"

**Comment by onnimonni** [comment]
+1

**Comment by dymissy** [comment]
+1

**Comment by amitailanciano** [comment]
There is an option in the Preferences window to include the machine names, perhaps in the next release we'll include or change this option to show _only_ the names instead.

![include_machine_names](https://cloud.githubusercontent.com/assets/1289466/7696043/919bf082-fdad-11e4-8295-00082d3f5062.png)

**Comment by Camoflame** [comment]
Note that above option doesn't use the Vagrantfile v.name variable. For me (OSX) it just adds "(default)" to the end of the folder name.

**Comment by amitailanciano** [comment]
@Camoflame if setting `.name` still produces `(default)` at the end of the folder name, then vagrant probably doesn't use that as the machine name in the `vagrant global-status` or `vagrant status` output, and that is the name we use. Alternatively, I just did a test using `.define`

`config.vm.define "some_custom_name"`

which does seem to do just that.

Have a look at http://stackoverflow.com/questions/17845637/vagrant-default-name for more info
