### ISSUE TITLE
Show current Vagrant version

### ISSUE THREAD

**Issue by adrenth-exed** [lanayotech/vagrant-manager#80]
Wouldn't it be great to have a menu-item (or somethingy) which reveals more information about the current installation of Vagrant? Yeah, I know ```vagrant version``` in Terminal does the job, but I think this should be a part of Vagrant Manager.

I think that that the command ```vagrant version``` gives enough information to put something together.
```
$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!
```

Since there is no auto-updating way for vagrant (afaik), this can notify users to update their vagrant. It can also provide a download link where the updated version of Vagrant can be downloaded.

Let me know what you think of it.

**Comment by amitailanciano** [comment]
this has been implemented in [release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0)
