### ISSUE TITLE
vagrant-manager does not source login profiles

### ISSUE THREAD

**Issue by delphyne** [lanayotech/vagrant-manager#84]
Our Vagrantfiles have a number of required environment variables, generally configured in users .bashrc and .bash_profile.  These variables point to code locations for mounted folders, etc.  When vagrant-manager runs its vagrant commands, it does so by running NSTask instances, which inherit their environment from the process that started them.

If you launch vagrant-manager in a shell process, you get the necessary variables, if you launch it from finder (or auto on login), it does not have a login shell, so it does not have the environment.

Similar failures would occur if Vagrant were installed in a location not in the system path, but in the PATH configured by the user's login profile.

Note:  I believe this is the same issue as https://github.com/lanayotech/vagrant-manager/issues/76, but i cannot confirm, since I don't have Homestead installed.

**Comment by amitailanciano** [comment]
this has been merged into [release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0)

**Comment by hvisage** [comment]
But does it source login/environment variables related to the specific Vagrantfile, and if so, where/how is this documented?
