### ISSUE TITLE
VAGRANT_DOTFILE_PATH of OS is ignored

### ISSUE THREAD

**Issue by gambolputty** [lanayotech/vagrant-manager#86]
Hello,

On my Windows 8 machine, the `VAGRANT_DOTFILE_PATH` is `.vagrant-desktop`.
When I run my Vagrant box with Vagrant Manager (Context menu >> MyMachine >> Up), this system variable is being ignored.

Instead, the old `.vagrant`-folder is newly created and the host runs form there.

Unfortunaly this makes using Vagrant Manager pointless to me, because I have to manage my hosts via custom DOTFILE_PATHs. Could you pleeeaase fix that?

Regars,
Gregor

**Comment by gambolputty** [comment]
Sorry, I accidentially opened this Issue at the wrong OS channel. Moving over to windows channel now.

**Comment by hvisage** [comment]
Actually, this is something very useful on MacOSX too ;)

**Comment by gambolputty** [comment]
@hvisage: Yes, I saw that a feature like this would be very handy since I'm developing on a Mac now too. This is why I reopened the issue.

**Comment by amitailanciano** [comment]
duplicate of #101
