### ISSUE TITLE
Menu items permanently disabled after alert is shown

### ISSUE THREAD

**Issue by amitailanciano** [lanayotech/vagrant-manager#87]
Steps to reproduce:

1.) Click either 'Check for Updates' or 'Check for Vagrant Updates'
2.) Before clicking 'OK' on the alert, toggle the menu
3.) Click 'OK' on the alert
4.) toggle the menu again, menu items are permanently disabled

Not sure how far this issue goes back, but it looks like 2.3.0 is also affected.

Hotfix will come soon

**Comment by strider72** [comment]
FYI -- I just upgraded to 2.4 and this started happening. I never saw it before this update.

**Comment by amitailanciano** [comment]
@strider72 those were my initial thoughts as well, however I tested it with a colleague of mine who never upgraded to 2.4, and the issue was present. We haven't had time to look into it yet, but we will put out a hotfix as soon as it's patched

**Comment by amitailanciano** [comment]
Fixed by [release 2.4.1](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.1)
