### ISSUE TITLE
Option to disable menu items (i.e. destroy VM)

### ISSUE THREAD

**Issue by xfxf** [lanayotech/vagrant-manager#89]
Hi there, curious whether it's possible to add an option to disable menu items.   Specifically I'd like to disable the 'destroy' option to avoid accidentally deleting a vagrant instance - which I did the other day by mis-clicking.

I feel this should be a much more deliberate task which isn't two clicks away at any time given how catastrophic it is :)

Would like this either as a global option one disables in the app Preferences, or as a per-VM thing.  If destroying a VM means I need to flick away a 'safety' option, then I think that's a good design worth considering.

I realise some people's use-cases for this might be regularly creating/destroying VM's, but I imagine I'm probably a fairly common use-case of having a bunch of ongoing VM's for local software development purposes.

**Comment by amitailanciano** [comment]
Right now there isn't any way to do that, and there is a confirmation dialog for the `destroy` option just in case you happen to mis-click.

I'll leave this open for a while for +1's, if it gets enough I'll consider adding it in

**Comment by strider72** [comment]
The interface would be awfully cluttered if you had options to micro-manage which items appear on the menus, but it seems reasonable to have an option to hide something like Destroy.

I had a similar incident with a different app recently -- deleting data when I meant to do something else.

+1 from me.

**Comment by chriswayoub** [comment]
I think between the confirmation dialog and the "Require option key for destroy" preference I'm going to consider this resolved.
