### ISSUE TITLE
Suspend/halt all VM's on logout 

### ISSUE THREAD

**Issue by aequitas** [lanayotech/vagrant-manager#90]
Would it be possible to add a option to suspend or halt all running VM's when the user logs out (and Vagrant Manager is closed)?

I often switch (logout/login, not fast-switch) between my 'work' and 'personal' account and ofter forget to halt all vagrant instances when logging out, causing resource/battery waste.

**Comment by maces** [comment]
highly +1 that

**Comment by esszett** [comment]
yes +1

**Comment by minac** [comment]
+1

**Comment by dknell** [comment]
What is the priority on this? I would think this feature is pretty important to anyone that uses vagrant on a daily basis.

**Comment by aequitas** [comment]
Maybe this could be easily implemented as a plugin. Since vagrant does not maintain a daemon or client app of sort it would require some work to make vagrant respond to a shutdown signal.

A plugin could run a process/daemon once a box is started (like landrush does) and on a shutdown signal iterate over all VM's and halt them. 

Optionally this feature could also fit well with existing Vagrant user frontends like: https://github.com/Bipsync/VagrantBar

**Comment by unikitty37** [comment]
I agree that this shouldn't be vagrant's responsibility — but the issue's filed against vagrant-manager, which already gets shutdown signals and would seem to be the right place to handle this. It already supports `All Machines > Suspend`, so would just need to call that before quitting if the system's going down.

**Comment by chriswayoub** [comment]
This feature has been implemented in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
