### ISSUE TITLE
Bookmark indicator improvement?

### ISSUE THREAD

**Issue by strider72** [lanayotech/vagrant-manager#92]
I think Macs have spoiled me for beautiful interfaces, but the [B] indication for bookmarks seems ugly to me.

Perhaps instead you could use a different shape "dot" for machines that are bookmarked.  For example, a green or red star -- or even a square -- rather than the green/red circle for a non-bookmarked machine.

**Comment by jjanusch** [comment]
Is there even a reason to have a visual indicator in each row? The bookmarks are already separated from the non-bookmarked items. You could just put in a divider to indicate where the bookmarks end, like is already between "Refresh" and the bookmarks. Don't include the divider if there are no bookmarks or there are no unbookmarked machines.

**Comment by strider72** [comment]
Well... the color indicator is already there, and useful, so incorporating the bookmarks there with shapes seems a good design that doesn't add any weight to the interface.

Nothing wrong with your idea, jjanusch.  Merely a  difference of asthetics.

**Comment by amitailanciano** [comment]
Improved by [release 2.4.1](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.1)
