### ISSUE TITLE
Last character cut off on some lines in output window

### ISSUE THREAD

**Issue by morganestes** [lanayotech/vagrant-manager#93]
The last character of certain lines are cut off when printed to the output window. Here's a screenshot of the word "currently" getting truncated:
![](https://cldup.com/EaOlonwHm1.png)

And this is what it looks like in the terminal:
![](https://cldup.com/noqAhHQCEa.png)

I'm running 2.4.1, but this has been happening since at least 2.3.

**Comment by chriswayoub** [comment]
Can you try the latest release (2.5.0) and let me know if you are still experiencing this issue? If it is, does it happen to all machines? Does it happen with all vagrant commands or only certain ones?

**Comment by morganestes** [comment]
Just tested it with 2.5.0 running a couple of commands (RDP and a custom command) and get the same problem of text cut off in the window (with some additional weird encoding issues), but when I copy the text out and paste it here, everything is present.

```
(B[m
 * keychain 2.8.1 ~ http://www.funtoo.org
 * Found existing ssh-agent: 508
 * Known ssh key: /Users/morganestes/.ssh/id_rsa

/usr/local/share/bash-completion/bash_completion: line 1812: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/share/bash-completion/bash_completion: line 1949: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
]1337;RemoteHost=morganestes@âï¸]1337;CurrentDir=/]1337;ShellIntegrationVersion=1Restarting memcached: memcached.
```
<img width="917" alt="screencapture-20151013t142336" src="https://cloud.githubusercontent.com/assets/110755/10465761/3a0ed8c0-71b6-11e5-908e-f2b9662d3ec6.png">

**Comment by briantully** [comment]
Yes, I've been noticing this as well, though for me it's pretty consistent in that it seems the last character of every line gets truncated in the window. Very strange. Running version 2.5.3 on Mac Yosemite 10.10.5
