### ISSUE TITLE
Homestead Vagrant Box

### ISSUE THREAD

**Issue by robjmills** [lanayotech/vagrant-manager#94]
The laravel/homestead Vagrant Box doesn't appear as a running VM when it's launched using the homestead utility http://laravel.com/docs/master/homestead

Running `vagrant global-status` does show it as "running" though

**Comment by chriswayoub** [comment]
Can you try the latest version of Vagrant Manager (2.5.0) and let me know if this is still an issue? If it is, would it be possible for you to provide some steps to reproduce what you are experiencing?

**Comment by Oscarteg** [comment]
I have the same problem. Homestead isn't shown as a running vagrant box but `vagrant global-status` does show it's running. 

I did `homestead up` and that's it.
