### ISSUE TITLE
Native OS X shortcuts doesn't work

### ISSUE THREAD

**Issue by frdmn** [lanayotech/vagrant-manager#97]
Shortcuts doesn't work in preferences windows like "Manage bookmarks" or "Manage custom commands".

I assume since they don't have a NSStatusBar, the shortcuts doesn't work as well (copy and paste or ⌘ + W to close the window).

**Comment by sogaiu** [comment]
It would also be nice if one could use the usual 'Select All' and 'Copy' commands via shortcuts where there is output from vagrant commands.

**Comment by amitailanciano** [comment]
this will be included in the next release
